#!/system/bin/sh
echo '230400' > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
echo '1305600' > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
echo 'ondemandX' > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
