#!/system/bin/sh
echo '122000' > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
echo '1382400' > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
echo 'ondemandX' > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
