#!/system/bin/sh
echo '230400' > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
echo '1228800' > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
echo 'ondemand' > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
